### ISSUE TITLE
Runtime panic with newer versions of Tiled maps (1.10+)

### ISSUE THREAD

**Issue by rust1cean** [not-fl3/macroquad#593]
Run will panic when loading map files made with newer versions of Tiled.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeJsonErr { msg: "Unexpected token Str expected [ ",
 line: 6, col: 2155 }'
```

The same error happened once before #252
'Tiled' program version - 1.10.1
'macroquad-tiled' package version - 0.1.1

**Comment by kmeshavkin** [comment]
Hey! Any updates for this? Seeing as macroquad-tiled is officially supported crate

**Comment by not-fl3** [comment]
Should be fixed in macroquad-tiled 0.2.1!

**Comment by kmeshavkin** [comment]
Checked it, I'm still getting the error, however seems like my issue was a bit different - instead of defining `collider` string property on tiles like you did in the example I used collision editor to define collisions for tiles. Instead of adding `properties` key with array of properties in `tilesets[0].tiles` map JSON it creates `objectgroup` key with object of different shapes and their descriptions.
Is defining collision layer in Tiled (and `objectgroup` property as a result) not supported yet? If it wasn't planned yet I can create an issue with more detailed description.

**Comment by not-fl3** [comment]
Sure, sounds like a brand new problem, feel free to open an issue!
